/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2021-02-22 07:08:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<link rel=\"stylesheet\" href=\"./adminResources/css/font-awesome.min.css\">\r\n");
      out.write("<div class=\"main-sidebar sidebar-style-2\">\r\n");
      out.write("\t<aside id=\"sidebar-wrapper\">\r\n");
      out.write("\t\t<div class=\"sidebar-brand\">\r\n");
      out.write("\t\t\t<a href=\"./index.jsp\">\r\n");
      out.write("\t\t\t<!--   <img alt=\"image\" src=\"adminResources/image/logo.png\" class=\"header-logo\" /> --> \r\n");
      out.write("\t\t\t<span class=\"logo-name\" >House Mart</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<ul class=\"sidebar-menu\">\r\n");
      out.write("\t\t\t<!-- <li class=\"menu-header\">Main</li> -->\r\n");
      out.write("\t\t<!--  \t<li class=\"dropdown active\"><a href=\"./index.jsp\"\r\n");
      out.write("\t\t\t\tclass=\"nav-link\"><i data-feather=\"home\"></i><span>Home</span></a>\r\n");
      out.write("\t\t\t</li> \r\n");
      out.write("\t\t\t-->\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"./datatable.jsp\"\r\n");
      out.write("\t\t\t\tclass=\"nav-link\"><i data-feather=\"layers\"></i><span>Manage User</span></a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--    class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"nav-link\"><i data-feather=\"book\"></i><span></span></a>\r\n");
      out.write("\t\t\t</li> -->\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"briefcase\"></i><span>Manage Categories</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"residential.jsp\">Add Category</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"commercial.jsp\">View Category</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"briefcase\"></i><span>Manage Property Type</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"residential.jsp\">Add Property Type</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"commercial.jsp\">View Property Type</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"briefcase\"></i><span>Manage Construction Status </span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"residential.jsp\">Add Construction Status</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"commercial.jsp\">View Construction Status</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"briefcase\"></i><span>Manage Location </span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"residential.jsp\">Add Location</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"commercial.jsp\">View Location</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"briefcase\"></i><span>Manage BHKs </span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"residential.jsp\">Add Bhks</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"commercial.jsp\">View Bhks</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"briefcase\"></i><span>Manage Property Area </span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"residential.jsp\">Add Property Area</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"commercial.jsp\">View Property Area</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"briefcase\"></i><span>Manage Property</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"residential.jsp\">Add Property</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"commercial.jsp\">View Property</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\"><a href=\"complain.jsp\"\r\n");
      out.write("\t\t\t\tclass=\"nav-link\"><i data-feather=\"alert-triangle\"></i><span>Manage Complains</span></a>\r\n");
      out.write("\t\t\t</li>  \r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"nav-link\"><i data-feather=\"alert-triangle\"></i><span>Manage Feedbacks</span></a>\r\n");
      out.write("\t\t\t</li>  \r\n");
      out.write("\t\t\t<!-- <li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"command\"></i><span>Apps</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"chat.html\">Chat</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"portfolio.html\">Portfolio</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"blog.html\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"calendar.html\">Calendar</a></li>\r\n");
      out.write("\t\t\t\t</ul></li> -->\r\n");
      out.write("\t\t<!-- \t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i data-feather=\"mail\"></i><span>Contact</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"email-inbox.html\">Inbox</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"email-compose.html\">Compose</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"email-read.html\">read</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<!-- <li class=\"menu-header\">UI Elements</li>\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i data-feather=\"copy\"></i><span>Basic\r\n");
      out.write("\t\t\t\t\t\tComponents</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"alert.html\">Alert</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"badge.html\">Badge</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"breadcrumb.html\">Breadcrumb</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"buttons.html\">Buttons</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"collapse.html\">Collapse</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"dropdown.html\">Dropdown</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"checkbox-and-radio.html\">Checkbox\r\n");
      out.write("\t\t\t\t\t\t\t&amp; Radios</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"list-group.html\">List Group</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"media-object.html\">Media\r\n");
      out.write("\t\t\t\t\t\t\tObject</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"navbar.html\">Navbar</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"pagination.html\">Pagination</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"popover.html\">Popover</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"progress.html\">Progress</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"tooltip.html\">Tooltip</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"flags.html\">Flag</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"typography.html\">Typography</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write(" -->\r\n");
      out.write("\t\t\t<!--  <li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"shopping-bag\"></i><span>Current Deals</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"avatar.html\">Avatar</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"card.html\">Card</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"modal.html\">Modal</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"sweet-alert.html\">Sweet\r\n");
      out.write("\t\t\t\t\t\t\tAlert</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"toastr.html\">Toastr</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"empty-state.html\">Empty\r\n");
      out.write("\t\t\t\t\t\t\tState</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"multiple-upload.html\">Multiple\r\n");
      out.write("\t\t\t\t\t\t\tUpload</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"pricing.html\">Pricing</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"tabs.html\">Tab</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<!-- <li><a class=\"nav-link\" href=\"blank.html\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"file\"></i><span>Blank Page</span></a></li>\r\n");
      out.write("\t\t\t<li class=\"menu-header\">Otika</li>\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"layout\"></i><span>Forms</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"basic-form.html\">Basic Form</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"forms-advanced-form.html\">Advanced\r\n");
      out.write("\t\t\t\t\t\t\tForm</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"forms-editor.html\">Editor</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"forms-validation.html\">Validation</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"form-wizard.html\">Form\r\n");
      out.write("\t\t\t\t\t\t\tWizard</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i data-feather=\"grid\"></i><span>Tables</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"basic-table.html\">Basic\r\n");
      out.write("\t\t\t\t\t\t\tTables</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"advance-table.html\">Advanced\r\n");
      out.write("\t\t\t\t\t\t\tTable</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"datatables.html\">Datatable</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"export-table.html\">Export\r\n");
      out.write("\t\t\t\t\t\t\tTable</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"editable-table.html\">Editable\r\n");
      out.write("\t\t\t\t\t\t\tTable</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"pie-chart\"></i><span>Charts</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"chart-amchart.html\">amChart</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"chart-apexchart.html\">apexchart</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"chart-echart.html\">eChart</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"chart-chartjs.html\">Chartjs</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"chart-sparkline.html\">Sparkline</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"chart-morris.html\">Morris</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"feather\"></i><span>Icons</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"icon-font-awesome.html\">Font\r\n");
      out.write("\t\t\t\t\t\t\tAwesome</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"icon-material.html\">Material\r\n");
      out.write("\t\t\t\t\t\t\tDesign</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"icon-ionicons.html\">Ion\r\n");
      out.write("\t\t\t\t\t\t\tIcons</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"icon-feather.html\">Feather\r\n");
      out.write("\t\t\t\t\t\t\tIcons</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"icon-weather-icon.html\">Weather\r\n");
      out.write("\t\t\t\t\t\t\tIcon</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"menu-header\">Media</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"image\"></i><span>Gallery</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"light-gallery.html\">Light\r\n");
      out.write("\t\t\t\t\t\t\tGallery</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"gallery1.html\">Gallery 2</a></li>\r\n");
      out.write("\t\t\t\t</ul></li> -->\r\n");
      out.write("\t\t\t<!-- \t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"nav-link\"><i data-feather=\"image\"></i><span>Gallery</span></a>\r\n");
      out.write("\t\t\t</li>  -->\r\n");
      out.write("\t\t\t<!-- <li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i data-feather=\"flag\"></i><span>Sliders</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"carousel.html\">Bootstrap Carousel.html</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"owl-carousel.html\">Owl\r\n");
      out.write("\t\t\t\t\t\t\tCarousel</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a class=\"nav-link\" href=\"timeline.html\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"sliders\"></i><span>Timeline</span></a></li>\r\n");
      out.write("\t\t\t<li class=\"menu-header\">Maps</li>\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i data-feather=\"map\"></i><span>Google\r\n");
      out.write("\t\t\t\t\t\tMaps</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"gmaps-advanced-route.html\">Advanced Route</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"gmaps-draggable-marker.html\">Draggable Marker</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"gmaps-geocoding.html\">Geocoding</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"gmaps-geolocation.html\">Geolocation</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"gmaps-marker.html\">Marker</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"gmaps-multiple-marker.html\">Multiple Marker</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"gmaps-route.html\">Route</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"gmaps-simple.html\">Simple</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a class=\"nav-link\" href=\"vector-map.html\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"map-pin\"></i><span>Vector Map</span></a></li>\r\n");
      out.write("\t\t\t<li class=\"menu-header\">Pages</li> \r\n");
      out.write("\t\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"users\"></i><span>Login/Registration</span></a>\r\n");
      out.write("\t\t\t\t <ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"auth-login.html\">Login</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"auth-register.html\">Register</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"auth-forgot-password.html\">Forgot Password</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"auth-reset-password.html\">Reset Password</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"subscribe.html\">Subscribe</a></li>\r\n");
      out.write("\t\t\t\t</ul> </li>-->\r\n");
      out.write("\t\t\t\t<!--   <li class=\"dropdown\"><a href=\"./register.jsp\"\r\n");
      out.write("\t\t\t\tclass=\"nav-link\"><i data-feather=\"users\"></i><span>Login/Registration</span></a>\r\n");
      out.write("\t\t\t</li> -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- <li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"alert-triangle\"></i><span>Errors</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"errors-503.html\">503</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"errors-403.html\">403</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"errors-404.html\">404</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"errors-500.html\">500</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"anchor\"></i><span>Other Pages</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"create-post.html\">Create\r\n");
      out.write("\t\t\t\t\t\t\tPost</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"posts.html\">Posts</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"profile.html\">Profile</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"nav-link\" href=\"invoice.html\">Invoice</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"menu-toggle nav-link has-dropdown\"><i\r\n");
      out.write("\t\t\t\t\tdata-feather=\"chevrons-down\"></i><span>Multilevel</span></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Menu 1</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"has-dropdown\">Menu\r\n");
      out.write("\t\t\t\t\t\t\t2</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Child Menu 1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"has-dropdown\">Child\r\n");
      out.write("\t\t\t\t\t\t\t\t\tMenu 2</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Child Menu 1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Child Menu 2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"> Child Menu 3</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write(" -->\t\t</ul>\r\n");
      out.write("\t</aside>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
